///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ocherednoisolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ocherednoisolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("d8a50b17-46a0-4f56-a688-4184a6355460")]
    public partial class ocherednoisolutionRepository : RepoGenBaseFolder
    {
        static ocherednoisolutionRepository instance = new ocherednoisolutionRepository();
        ocherednoisolutionRepositoryFolders.ИнформацияAppFolder _информация;
        ocherednoisolutionRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder _geotech3d7геологиямаркшейде;
        ocherednoisolutionRepositoryFolders.GeoTechAppFolder _geotech;
        ocherednoisolutionRepositoryFolders.GeoTech3DAppFolder _geotech3d;
        ocherednoisolutionRepositoryFolders.GeoTech3D1AppFolder _geotech3d1;
        ocherednoisolutionRepositoryFolders.GEOTECH3D2AppFolder _geotech3d2;
        ocherednoisolutionRepositoryFolders.ОткрытиеAppFolder _открытие;
        ocherednoisolutionRepositoryFolders.List1000AppFolder _list1000;
        ocherednoisolutionRepositoryFolders.GEOTECH3D3AppFolder _geotech3d3;
        ocherednoisolutionRepositoryFolders.GEOTECH3D4AppFolder _geotech3d4;

        /// <summary>
        /// Gets the singleton class instance representing the ocherednoisolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("d8a50b17-46a0-4f56-a688-4184a6355460")]
        public static ocherednoisolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ocherednoisolutionRepository() 
            : base("ocherednoisolutionRepository", "/", null, 0, false, "d8a50b17-46a0-4f56-a688-4184a6355460", ".\\RepositoryImages\\ocherednoisolutionRepositoryd8a50b17.rximgres")
        {
            _информация = new ocherednoisolutionRepositoryFolders.ИнформацияAppFolder(this);
            _geotech3d7геологиямаркшейде = new ocherednoisolutionRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder(this);
            _geotech = new ocherednoisolutionRepositoryFolders.GeoTechAppFolder(this);
            _geotech3d = new ocherednoisolutionRepositoryFolders.GeoTech3DAppFolder(this);
            _geotech3d1 = new ocherednoisolutionRepositoryFolders.GeoTech3D1AppFolder(this);
            _geotech3d2 = new ocherednoisolutionRepositoryFolders.GEOTECH3D2AppFolder(this);
            _открытие = new ocherednoisolutionRepositoryFolders.ОткрытиеAppFolder(this);
            _list1000 = new ocherednoisolutionRepositoryFolders.List1000AppFolder(this);
            _geotech3d3 = new ocherednoisolutionRepositoryFolders.GEOTECH3D3AppFolder(this);
            _geotech3d4 = new ocherednoisolutionRepositoryFolders.GEOTECH3D4AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d8a50b17-46a0-4f56-a688-4184a6355460")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Информация folder.
        /// </summary>
        [RepositoryFolder("e3f0acec-31f2-4cf0-87ef-bd9c2c3adc1e")]
        public virtual ocherednoisolutionRepositoryFolders.ИнформацияAppFolder Информация
        {
            get { return _информация; }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейде folder.
        /// </summary>
        [RepositoryFolder("7e2d82b3-1a6c-40fe-9a64-80dd1af58747")]
        public virtual ocherednoisolutionRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder GeoTech3D7ГеологияМаркшейде
        {
            get { return _geotech3d7геологиямаркшейде; }
        }

        /// <summary>
        /// The GeoTech folder.
        /// </summary>
        [RepositoryFolder("5c554a99-4983-44af-a385-9c66ec0630ea")]
        public virtual ocherednoisolutionRepositoryFolders.GeoTechAppFolder GeoTech
        {
            get { return _geotech; }
        }

        /// <summary>
        /// The GeoTech3D folder.
        /// </summary>
        [RepositoryFolder("3cac9127-946c-432a-87c6-3545fa8105a5")]
        public virtual ocherednoisolutionRepositoryFolders.GeoTech3DAppFolder GeoTech3D
        {
            get { return _geotech3d; }
        }

        /// <summary>
        /// The GeoTech3D1 folder.
        /// </summary>
        [RepositoryFolder("0c4364ac-8fd0-4a74-8a2b-8009ab2b4797")]
        public virtual ocherednoisolutionRepositoryFolders.GeoTech3D1AppFolder GeoTech3D1
        {
            get { return _geotech3d1; }
        }

        /// <summary>
        /// The GEOTECH3D2 folder.
        /// </summary>
        [RepositoryFolder("8be1056f-577c-404d-8716-2a89ee815015")]
        public virtual ocherednoisolutionRepositoryFolders.GEOTECH3D2AppFolder GEOTECH3D2
        {
            get { return _geotech3d2; }
        }

        /// <summary>
        /// The Открытие folder.
        /// </summary>
        [RepositoryFolder("b9e87e9a-44be-4553-867e-4ef744dbddec")]
        public virtual ocherednoisolutionRepositoryFolders.ОткрытиеAppFolder Открытие
        {
            get { return _открытие; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("aa157abf-7d02-4b16-8692-8ab931100f52")]
        public virtual ocherednoisolutionRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The GEOTECH3D3 folder.
        /// </summary>
        [RepositoryFolder("17f39feb-b86e-44cb-9e61-c7d6f4ecd3b6")]
        public virtual ocherednoisolutionRepositoryFolders.GEOTECH3D3AppFolder GEOTECH3D3
        {
            get { return _geotech3d3; }
        }

        /// <summary>
        /// The GEOTECH3D4 folder.
        /// </summary>
        [RepositoryFolder("b00d3f11-363c-42dc-a89e-f916a563e29f")]
        public virtual ocherednoisolutionRepositoryFolders.GEOTECH3D4AppFolder GEOTECH3D4
        {
            get { return _geotech3d4; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class ocherednoisolutionRepositoryFolders
    {
        /// <summary>
        /// The ИнформацияAppFolder folder.
        /// </summary>
        [RepositoryFolder("e3f0acec-31f2-4cf0-87ef-bd9c2c3adc1e")]
        public partial class ИнформацияAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;

            /// <summary>
            /// Creates a new Информация  folder.
            /// </summary>
            public ИнформацияAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Информация", "/form[@title='Информация']", parentFolder, 30000, null, true, "e3f0acec-31f2-4cf0-87ef-bd9c2c3adc1e", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "?/?/element[@instance='0']/button[@text='О&К']", 30000, null, "72d4ddbe-08de-471b-b833-7f8005b84fb1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3f0acec-31f2-4cf0-87ef-bd9c2c3adc1e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3f0acec-31f2-4cf0-87ef-bd9c2c3adc1e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("72d4ddbe-08de-471b-b833-7f8005b84fb1")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("72d4ddbe-08de-471b-b833-7f8005b84fb1")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейдеAppFolder folder.
        /// </summary>
        [RepositoryFolder("7e2d82b3-1a6c-40fe-9a64-80dd1af58747")]
        public partial class GeoTech3D7ГеологияМаркшейдеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _символInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _objinspInfo;
            RepoItemInfo _propokbtnInfo;
            RepoItemInfo _form65280Info;
            RepoItemInfo _someelement1Info;
            RepoItemInfo _действияInfo;

            /// <summary>
            /// Creates a new GeoTech3D7ГеологияМаркшейде  folder.
            /// </summary>
            public GeoTech3D7ГеологияМаркшейдеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D7ГеологияМаркшейде", "/form[@name='MainForm' and @title~'^GeoTech-3D\\ 7\\ \\|\\ \\ \\ \\ \\ \\ \\ \\ Гео']", parentFolder, 30000, null, true, "7e2d82b3-1a6c-40fe-9a64-80dd1af58747", "")
            {
                _символInfo = new RepoItemInfo(this, "Символ", "?/?/menuitem[@name='SymbolItm']", 30000, null, "7dec965d-5b97-44a7-8aa0-42d7be79b224");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element[@name='LeftControlBar']/form[@title='Объекты']/element[1]", 30000, null, "66fa5c7b-cf6e-4192-9338-d06eaac144c4");
                _objinspInfo = new RepoItemInfo(this, "ObjInsp", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']/?/?/container[@name='PropertyTab']//tree[@name='ObjInsp']", 30000, null, "f9e2828e-0da0-4b36-a2b4-01d02f551950");
                _propokbtnInfo = new RepoItemInfo(this, "PropOkBtn", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']//element[@name='PropOkBtn']", 30000, null, "d2f7e8dc-b9ec-4e9f-b8d2-d7f3bbf99422");
                _form65280Info = new RepoItemInfo(this, "Form65280", "form[@name='MDIChild']", 30000, null, "92172010-bd99-41b6-bfef-9db575f1289a");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "element[@name='LeftControlBar']/form[@title='Редактирование']/element[5]", 30000, null, "eca44e7d-9ecd-4cac-ba72-e488f06b0ec7");
                _действияInfo = new RepoItemInfo(this, "Действия", "?/?/menuitem[@name='miMainActions']", 30000, null, "c0138c09-0ebd-4409-a1c9-e0481432f2bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7e2d82b3-1a6c-40fe-9a64-80dd1af58747")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7e2d82b3-1a6c-40fe-9a64-80dd1af58747")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Символ item.
            /// </summary>
            [RepositoryItem("7dec965d-5b97-44a7-8aa0-42d7be79b224")]
            public virtual Ranorex.MenuItem Символ
            {
                get
                {
                    return _символInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Символ item info.
            /// </summary>
            [RepositoryItemInfo("7dec965d-5b97-44a7-8aa0-42d7be79b224")]
            public virtual RepoItemInfo СимволInfo
            {
                get
                {
                    return _символInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("66fa5c7b-cf6e-4192-9338-d06eaac144c4")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("66fa5c7b-cf6e-4192-9338-d06eaac144c4")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The ObjInsp item.
            /// </summary>
            [RepositoryItem("f9e2828e-0da0-4b36-a2b4-01d02f551950")]
            public virtual Ranorex.Tree ObjInsp
            {
                get
                {
                    return _objinspInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The ObjInsp item info.
            /// </summary>
            [RepositoryItemInfo("f9e2828e-0da0-4b36-a2b4-01d02f551950")]
            public virtual RepoItemInfo ObjInspInfo
            {
                get
                {
                    return _objinspInfo;
                }
            }

            /// <summary>
            /// The PropOkBtn item.
            /// </summary>
            [RepositoryItem("d2f7e8dc-b9ec-4e9f-b8d2-d7f3bbf99422")]
            public virtual Ranorex.Unknown PropOkBtn
            {
                get
                {
                    return _propokbtnInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The PropOkBtn item info.
            /// </summary>
            [RepositoryItemInfo("d2f7e8dc-b9ec-4e9f-b8d2-d7f3bbf99422")]
            public virtual RepoItemInfo PropOkBtnInfo
            {
                get
                {
                    return _propokbtnInfo;
                }
            }

            /// <summary>
            /// The Form65280 item.
            /// </summary>
            [RepositoryItem("92172010-bd99-41b6-bfef-9db575f1289a")]
            public virtual Ranorex.Form Form65280
            {
                get
                {
                    return _form65280Info.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Form65280 item info.
            /// </summary>
            [RepositoryItemInfo("92172010-bd99-41b6-bfef-9db575f1289a")]
            public virtual RepoItemInfo Form65280Info
            {
                get
                {
                    return _form65280Info;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("eca44e7d-9ecd-4cac-ba72-e488f06b0ec7")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("eca44e7d-9ecd-4cac-ba72-e488f06b0ec7")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }

            /// <summary>
            /// The Действия item.
            /// </summary>
            [RepositoryItem("c0138c09-0ebd-4409-a1c9-e0481432f2bc")]
            public virtual Ranorex.MenuItem Действия
            {
                get
                {
                    return _действияInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Действия item info.
            /// </summary>
            [RepositoryItemInfo("c0138c09-0ebd-4409-a1c9-e0481432f2bc")]
            public virtual RepoItemInfo ДействияInfo
            {
                get
                {
                    return _действияInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTechAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c554a99-4983-44af-a385-9c66ec0630ea")]
        public partial class GeoTechAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _создатьctrlplusnInfo;
            RepoItemInfo _импортизфайлаInfo;

            /// <summary>
            /// Creates a new GeoTech  folder.
            /// </summary>
            public GeoTechAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech", "/contextmenu[@processname='GeoTech']", parentFolder, 30000, null, false, "5c554a99-4983-44af-a385-9c66ec0630ea", "")
            {
                _создатьctrlplusnInfo = new RepoItemInfo(this, "СоздатьCtrlPlusN", "?/?/menuitem[@accessiblename='Создать...Ctrl+N']", 30000, null, "461d7115-43ec-447e-87c6-afd1fab1aa94");
                _импортизфайлаInfo = new RepoItemInfo(this, "ИмпортИзФайла", "?/?/menuitem[@accessiblename='Импорт из файла']", 30000, null, "0769496c-09f6-4027-8a2d-e9c4b766d8b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c554a99-4983-44af-a385-9c66ec0630ea")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c554a99-4983-44af-a385-9c66ec0630ea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item.
            /// </summary>
            [RepositoryItem("461d7115-43ec-447e-87c6-afd1fab1aa94")]
            public virtual Ranorex.MenuItem СоздатьCtrlPlusN
            {
                get
                {
                    return _создатьctrlplusnInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item info.
            /// </summary>
            [RepositoryItemInfo("461d7115-43ec-447e-87c6-afd1fab1aa94")]
            public virtual RepoItemInfo СоздатьCtrlPlusNInfo
            {
                get
                {
                    return _создатьctrlplusnInfo;
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item.
            /// </summary>
            [RepositoryItem("0769496c-09f6-4027-8a2d-e9c4b766d8b2")]
            public virtual Ranorex.MenuItem ИмпортИзФайла
            {
                get
                {
                    return _импортизфайлаInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item info.
            /// </summary>
            [RepositoryItemInfo("0769496c-09f6-4027-8a2d-e9c4b766d8b2")]
            public virtual RepoItemInfo ИмпортИзФайлаInfo
            {
                get
                {
                    return _импортизфайлаInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("3cac9127-946c-432a-87c6-3545fa8105a5")]
        public partial class GeoTech3DAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sbtcreateprojectInfo;

            /// <summary>
            /// Creates a new GeoTech3D  folder.
            /// </summary>
            public GeoTech3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D", "/form[@name='DualListDlg']", parentFolder, 30000, null, true, "3cac9127-946c-432a-87c6-3545fa8105a5", "")
            {
                _sbtcreateprojectInfo = new RepoItemInfo(this, "SbtCreateProject", "button[@name='sbtCreateProject']", 30000, null, "1513eed2-21dc-410e-a9f8-002538c09f00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3cac9127-946c-432a-87c6-3545fa8105a5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3cac9127-946c-432a-87c6-3545fa8105a5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SbtCreateProject item.
            /// </summary>
            [RepositoryItem("1513eed2-21dc-410e-a9f8-002538c09f00")]
            public virtual Ranorex.Button SbtCreateProject
            {
                get
                {
                    return _sbtcreateprojectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SbtCreateProject item info.
            /// </summary>
            [RepositoryItemInfo("1513eed2-21dc-410e-a9f8-002538c09f00")]
            public virtual RepoItemInfo SbtCreateProjectInfo
            {
                get
                {
                    return _sbtcreateprojectInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D1AppFolder folder.
        /// </summary>
        [RepositoryFolder("0c4364ac-8fd0-4a74-8a2b-8009ab2b4797")]
        public partial class GeoTech3D1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _применитьInfo;

            /// <summary>
            /// Creates a new GeoTech3D1  folder.
            /// </summary>
            public GeoTech3D1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D1", "/form[@name='NewNameProj']", parentFolder, 30000, null, true, "0c4364ac-8fd0-4a74-8a2b-8009ab2b4797", "")
            {
                _применитьInfo = new RepoItemInfo(this, "Применить", "button[@name='btnApply']", 30000, null, "0a8884f9-59ba-42fd-b029-5fba67a3bd5a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0c4364ac-8fd0-4a74-8a2b-8009ab2b4797")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0c4364ac-8fd0-4a74-8a2b-8009ab2b4797")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Применить item.
            /// </summary>
            [RepositoryItem("0a8884f9-59ba-42fd-b029-5fba67a3bd5a")]
            public virtual Ranorex.Button Применить
            {
                get
                {
                    return _применитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Применить item info.
            /// </summary>
            [RepositoryItemInfo("0a8884f9-59ba-42fd-b029-5fba67a3bd5a")]
            public virtual RepoItemInfo ПрименитьInfo
            {
                get
                {
                    return _применитьInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D2AppFolder folder.
        /// </summary>
        [RepositoryFolder("8be1056f-577c-404d-8716-2a89ee815015")]
        public partial class GEOTECH3D2AppFolder : RepoGenBaseFolder
        {
            ocherednoisolutionRepositoryFolders.TabbedNotebook1Folder _tabbednotebook1;
            RepoItemInfo _выполнитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D2  folder.
            /// </summary>
            public GEOTECH3D2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D2", "/form[@name='GeoOptions']", parentFolder, 30000, null, true, "8be1056f-577c-404d-8716-2a89ee815015", "")
            {
                _tabbednotebook1 = new ocherednoisolutionRepositoryFolders.TabbedNotebook1Folder(this);
                _выполнитьInfo = new RepoItemInfo(this, "Выполнить", "button[@name='OKBtn']", 30000, null, "a6e2fed3-d9c0-4c87-8c6e-14fb02e79857");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8be1056f-577c-404d-8716-2a89ee815015")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8be1056f-577c-404d-8716-2a89ee815015")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Выполнить item.
            /// </summary>
            [RepositoryItem("a6e2fed3-d9c0-4c87-8c6e-14fb02e79857")]
            public virtual Ranorex.Button Выполнить
            {
                get
                {
                    return _выполнитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Выполнить item info.
            /// </summary>
            [RepositoryItemInfo("a6e2fed3-d9c0-4c87-8c6e-14fb02e79857")]
            public virtual RepoItemInfo ВыполнитьInfo
            {
                get
                {
                    return _выполнитьInfo;
                }
            }

            /// <summary>
            /// The TabbedNotebook1 folder.
            /// </summary>
            [RepositoryFolder("6d052996-3bea-4d7e-af1b-29a4699ebbc2")]
            public virtual ocherednoisolutionRepositoryFolders.TabbedNotebook1Folder TabbedNotebook1
            {
                get { return _tabbednotebook1; }
            }
        }

        /// <summary>
        /// The TabbedNotebook1Folder folder.
        /// </summary>
        [RepositoryFolder("6d052996-3bea-4d7e-af1b-29a4699ebbc2")]
        public partial class TabbedNotebook1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _xmaxeditInfo;
            RepoItemInfo _xmineditInfo;
            RepoItemInfo _ymaxeditInfo;
            RepoItemInfo _ymineditInfo;
            RepoItemInfo _zmaxeditInfo;
            RepoItemInfo _zmineditInfo;

            /// <summary>
            /// Creates a new TabbedNotebook1  folder.
            /// </summary>
            public TabbedNotebook1Folder(RepoGenBaseFolder parentFolder) :
                    base("TabbedNotebook1", "tabpagelist[@name='TabbedNotebook1']", parentFolder, 30000, null, false, "6d052996-3bea-4d7e-af1b-29a4699ebbc2", "")
            {
                _xmaxeditInfo = new RepoItemInfo(this, "XmaxEdit", ".//text[@name='XmaxEdit']", 30000, null, "63d77f82-c67d-4c27-ad62-19d3db0a4b53");
                _xmineditInfo = new RepoItemInfo(this, "XminEdit", ".//text[@name='XminEdit']", 30000, null, "f72631de-fd4c-42fb-ba9b-c8d2839f0349");
                _ymaxeditInfo = new RepoItemInfo(this, "YmaxEdit", ".//text[@name='YmaxEdit']", 30000, null, "8156fb69-901a-4d19-b17d-2c2928d92ed0");
                _ymineditInfo = new RepoItemInfo(this, "YminEdit", ".//text[@name='YminEdit']", 30000, null, "1137adba-72dd-408b-9c84-56b656e121c9");
                _zmaxeditInfo = new RepoItemInfo(this, "ZmaxEdit", ".//text[@name='ZmaxEdit']", 30000, null, "63fbc56b-b65f-4668-8902-a969e76d2bcb");
                _zmineditInfo = new RepoItemInfo(this, "ZminEdit", ".//text[@name='ZminEdit']", 30000, null, "c553ee0d-2d3c-4261-81c0-0839a860a821");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d052996-3bea-4d7e-af1b-29a4699ebbc2")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d052996-3bea-4d7e-af1b-29a4699ebbc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XmaxEdit item.
            /// </summary>
            [RepositoryItem("63d77f82-c67d-4c27-ad62-19d3db0a4b53")]
            public virtual Ranorex.Text XmaxEdit
            {
                get
                {
                    return _xmaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("63d77f82-c67d-4c27-ad62-19d3db0a4b53")]
            public virtual RepoItemInfo XmaxEditInfo
            {
                get
                {
                    return _xmaxeditInfo;
                }
            }

            /// <summary>
            /// The XminEdit item.
            /// </summary>
            [RepositoryItem("f72631de-fd4c-42fb-ba9b-c8d2839f0349")]
            public virtual Ranorex.Text XminEdit
            {
                get
                {
                    return _xmineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XminEdit item info.
            /// </summary>
            [RepositoryItemInfo("f72631de-fd4c-42fb-ba9b-c8d2839f0349")]
            public virtual RepoItemInfo XminEditInfo
            {
                get
                {
                    return _xmineditInfo;
                }
            }

            /// <summary>
            /// The YmaxEdit item.
            /// </summary>
            [RepositoryItem("8156fb69-901a-4d19-b17d-2c2928d92ed0")]
            public virtual Ranorex.Text YmaxEdit
            {
                get
                {
                    return _ymaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("8156fb69-901a-4d19-b17d-2c2928d92ed0")]
            public virtual RepoItemInfo YmaxEditInfo
            {
                get
                {
                    return _ymaxeditInfo;
                }
            }

            /// <summary>
            /// The YminEdit item.
            /// </summary>
            [RepositoryItem("1137adba-72dd-408b-9c84-56b656e121c9")]
            public virtual Ranorex.Text YminEdit
            {
                get
                {
                    return _ymineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YminEdit item info.
            /// </summary>
            [RepositoryItemInfo("1137adba-72dd-408b-9c84-56b656e121c9")]
            public virtual RepoItemInfo YminEditInfo
            {
                get
                {
                    return _ymineditInfo;
                }
            }

            /// <summary>
            /// The ZmaxEdit item.
            /// </summary>
            [RepositoryItem("63fbc56b-b65f-4668-8902-a969e76d2bcb")]
            public virtual Ranorex.Text ZmaxEdit
            {
                get
                {
                    return _zmaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ZmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("63fbc56b-b65f-4668-8902-a969e76d2bcb")]
            public virtual RepoItemInfo ZmaxEditInfo
            {
                get
                {
                    return _zmaxeditInfo;
                }
            }

            /// <summary>
            /// The ZminEdit item.
            /// </summary>
            [RepositoryItem("c553ee0d-2d3c-4261-81c0-0839a860a821")]
            public virtual Ranorex.Text ZminEdit
            {
                get
                {
                    return _zmineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ZminEdit item info.
            /// </summary>
            [RepositoryItemInfo("c553ee0d-2d3c-4261-81c0-0839a860a821")]
            public virtual RepoItemInfo ZminEditInfo
            {
                get
                {
                    return _zmineditInfo;
                }
            }
        }

        /// <summary>
        /// The ОткрытиеAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9e87e9a-44be-4553-867e-4ef744dbddec")]
        public partial class ОткрытиеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _combobox1136Info;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonоткрытьInfo;

            /// <summary>
            /// Creates a new Открытие  folder.
            /// </summary>
            public ОткрытиеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Открытие", "/form[@title='Открытие']", parentFolder, 30000, null, true, "b9e87e9a-44be-4553-867e-4ef744dbddec", "")
            {
                _combobox1136Info = new RepoItemInfo(this, "ComboBox1136", "combobox[@controlid='1136']", 30000, null, "f2518b15-2427-49d4-9102-0cd6d8e28ee1");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='1']/text[@automationid='System.ItemNameDisplay']", 30000, null, "a1206fb6-fb14-4957-b5ba-09a58a06b122");
                _buttonоткрытьInfo = new RepoItemInfo(this, "ButtonОткрыть", "button[@text='&Открыть']", 30000, null, "b427292f-c760-4dbf-a4c1-a0759e2a6c99");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9e87e9a-44be-4553-867e-4ef744dbddec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9e87e9a-44be-4553-867e-4ef744dbddec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboBox1136 item.
            /// </summary>
            [RepositoryItem("f2518b15-2427-49d4-9102-0cd6d8e28ee1")]
            public virtual Ranorex.ComboBox ComboBox1136
            {
                get
                {
                    return _combobox1136Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1136 item info.
            /// </summary>
            [RepositoryItemInfo("f2518b15-2427-49d4-9102-0cd6d8e28ee1")]
            public virtual RepoItemInfo ComboBox1136Info
            {
                get
                {
                    return _combobox1136Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("a1206fb6-fb14-4957-b5ba-09a58a06b122")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("a1206fb6-fb14-4957-b5ba-09a58a06b122")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonОткрыть item.
            /// </summary>
            [RepositoryItem("b427292f-c760-4dbf-a4c1-a0759e2a6c99")]
            public virtual Ranorex.Button ButtonОткрыть
            {
                get
                {
                    return _buttonоткрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОткрыть item info.
            /// </summary>
            [RepositoryItemInfo("b427292f-c760-4dbf-a4c1-a0759e2a6c99")]
            public virtual RepoItemInfo ButtonОткрытьInfo
            {
                get
                {
                    return _buttonоткрытьInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("aa157abf-7d02-4b16-8692-8ab931100f52")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _файлыautocad2004dxfasteriskdxfInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "aa157abf-7d02-4b16-8692-8ab931100f52", "")
            {
                _файлыautocad2004dxfasteriskdxfInfo = new RepoItemInfo(this, "ФайлыAutoCAD2004DXFAsteriskDxf", "listitem[@text~'^Файлы\\ AutoCAD\\ 2004\\ DXF\\ \\(\\*']", 30000, null, "7d174916-9edd-44e4-8e0c-ab93d5c57f00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa157abf-7d02-4b16-8692-8ab931100f52")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa157abf-7d02-4b16-8692-8ab931100f52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item.
            /// </summary>
            [RepositoryItem("7d174916-9edd-44e4-8e0c-ab93d5c57f00")]
            public virtual Ranorex.ListItem ФайлыAutoCAD2004DXFAsteriskDxf
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item info.
            /// </summary>
            [RepositoryItemInfo("7d174916-9edd-44e4-8e0c-ab93d5c57f00")]
            public virtual RepoItemInfo ФайлыAutoCAD2004DXFAsteriskDxfInfo
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D3AppFolder folder.
        /// </summary>
        [RepositoryFolder("17f39feb-b86e-44cb-9e61-c7d6f4ecd3b6")]
        public partial class GEOTECH3D3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _геодезическиеInfo;
            RepoItemInfo _импортInfo;

            /// <summary>
            /// Creates a new GEOTECH3D3  folder.
            /// </summary>
            public GEOTECH3D3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D3", "/form[@name='ImportDXFOption']", parentFolder, 30000, null, true, "17f39feb-b86e-44cb-9e61-c7d6f4ecd3b6", "")
            {
                _геодезическиеInfo = new RepoItemInfo(this, "Геодезические", "?/?/radiobutton[@name='rbGeod']", 30000, null, "dbf7b10f-9609-4a7c-91fa-b8a46472d5e1");
                _импортInfo = new RepoItemInfo(this, "Импорт", "button[@name='btnOK']", 30000, null, "49972248-8424-4dd8-8d05-bf1845e86426");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17f39feb-b86e-44cb-9e61-c7d6f4ecd3b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17f39feb-b86e-44cb-9e61-c7d6f4ecd3b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Геодезические item.
            /// </summary>
            [RepositoryItem("dbf7b10f-9609-4a7c-91fa-b8a46472d5e1")]
            public virtual Ranorex.RadioButton Геодезические
            {
                get
                {
                    return _геодезическиеInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Геодезические item info.
            /// </summary>
            [RepositoryItemInfo("dbf7b10f-9609-4a7c-91fa-b8a46472d5e1")]
            public virtual RepoItemInfo ГеодезическиеInfo
            {
                get
                {
                    return _геодезическиеInfo;
                }
            }

            /// <summary>
            /// The Импорт item.
            /// </summary>
            [RepositoryItem("49972248-8424-4dd8-8d05-bf1845e86426")]
            public virtual Ranorex.Button Импорт
            {
                get
                {
                    return _импортInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Импорт item info.
            /// </summary>
            [RepositoryItemInfo("49972248-8424-4dd8-8d05-bf1845e86426")]
            public virtual RepoItemInfo ИмпортInfo
            {
                get
                {
                    return _импортInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D4AppFolder folder.
        /// </summary>
        [RepositoryFolder("b00d3f11-363c-42dc-a89e-f916a563e29f")]
        public partial class GEOTECH3D4AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _продолжитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D4  folder.
            /// </summary>
            public GEOTECH3D4AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D4", "/form[@name='frmImportDxfShift']", parentFolder, 30000, null, true, "b00d3f11-363c-42dc-a89e-f916a563e29f", "")
            {
                _продолжитьInfo = new RepoItemInfo(this, "Продолжить", "button[@name='Button1']", 30000, null, "fac853f5-6ebf-4061-8aec-5802ab75cdf0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b00d3f11-363c-42dc-a89e-f916a563e29f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b00d3f11-363c-42dc-a89e-f916a563e29f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Продолжить item.
            /// </summary>
            [RepositoryItem("fac853f5-6ebf-4061-8aec-5802ab75cdf0")]
            public virtual Ranorex.Button Продолжить
            {
                get
                {
                    return _продолжитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Продолжить item info.
            /// </summary>
            [RepositoryItemInfo("fac853f5-6ebf-4061-8aec-5802ab75cdf0")]
            public virtual RepoItemInfo ПродолжитьInfo
            {
                get
                {
                    return _продолжитьInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}